# in this program, user will be asked about which python function needs 
# to be created, and then the program will provide a code generated by LLM
# after creation that function we will store that function and ask LLM to porovide the 
# dcoumentation for that function, and then we will store that documentation in a file named "documentation.txt"
# and as third step we will test out this entire function by asking LLM to provide some test cases for that function and then we will run those test cases and store the results in a file named "test_results.txt"
# lets use GEMINI for this task
from py_compile import main
import os
import logging
from typing import List
from click import prompt
#from dotenv import load_dotenv
from langchain_google_genai  import GoogleGenerativeAI, ChatGoogleGenerativeAI



# ============================================================================
# CONFIGURATION & SETUP
# ============================================================================

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# initialize the llm
llm = ChatGoogleGenerativeAI(
     model="gemini-2.5-flash",
     temperature=0.7
)

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
        

# ============================================================================
# UTILITY FUNCTIONS
# ============================================================================

    
def main():
    # Step 1: Get function description from the user
    user_input = input("Enter a description of the Python function you want to create: ")
    logger.info("Generating function code...")
    prompt = f"Write a Python function that {user_input}."
    response = llm.invoke(prompt)

    # Step 2: Generate function code
    print("\nGenerated Function Code:\n")
    function_code = response.text.strip()
    #print(function_code)

    # Step 3: Generate documentation for the function
    logger.info("Generating documentation for the function...")
    doc_prompt = f"Write documentation for the following Python function:\n\n{function_code}"
    doc_response = llm.invoke(doc_prompt).text.strip()
    print("\nGenerated Documentation:\n")
    documentation = doc_response

    with open("documentation.txt", "w", encoding="utf-8") as doc_file:
        doc_file.write(response.text.strip()+ documentation)
        logger.info("Documentation saved successfully to 'documentation.txt'.")


    # Step 4: Generate test cases for the function
 
            
if __name__ == "__main__":    
    main()